# Generated by Django 5.1.6 on 2025-02-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Event'), (2, 'Snapshot')], default=1)),
                ('name', models.CharField(max_length=50)),
                ('object_id', models.PositiveBigIntegerField()),
                ('applied_to_version', models.PositiveBigIntegerField()),
                ('state', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('type', 1)), fields=('object_id', 'applied_to_version'), name='record_unique_applied_to_version')],
            },
        ),
    ]
