# Generated by Django 5.1.6 on 2025-02-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sourcery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Event'), (2, 'Snapshot')], default=1),
        ),
    ]
