# Generated by Django 4.2.19 on 2025-03-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sourcery', '0002_alter_eventrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
