# Generated by Django 5.1.7 on 2025-03-06 18:59

from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ('django_sourcery', '0002_alter_eventrecord_id'),
    ]

    operations = [
    ] + [
        migrations.RemoveConstraint(
            model_name='eventrecord',
            name='record_unique_applied_to_version',
        ),
        migrations.AddConstraint(
            model_name='eventrecord',
            constraint=models.UniqueConstraint(fields=('object_id', 'applied_to_version'), name='record_unique_applied_to_version'),
        ),
    ] if "postgres" not in connection.settings_dict["ENGINE"] else []
