# Generated by Django 5.1.6 on 2025-02-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sourcery', '0002_eventrecord_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventrecord',
            name='record_unique_originator_version',
        ),
        migrations.AddConstraint(
            model_name='eventrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 1)), fields=('originator_id', 'originator_version'), name='record_unique_originator_version'),
        ),
    ]
