# Generated by Django 5.1.6 on 2025-02-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
