# Generated by Django 5.1.6 on 2025-02-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
